"""Reusable RealSense Cable detection pipeline (library).

Auto-generated by the RealSense Cable Video Analyzer.
Self-contained: needs only opencv-python + numpy.

This file bakes in NO settings. Hand it a JSON config
(exported alongside as <name>_config.json, or any config
the analyzer saved) and it reproduces that exact pipeline:

    import cv2
    from exported_pipeline_lib import load_pipeline
    pipe = load_pipeline('exported_pipeline_config.json')
    mask = pipe.final_mask(cv2.imread('photo.jpg'))

See the exported <name>_README.md for the full guide.
"""
import os
import json
import cv2
import numpy as np

# ----------------------------------------------------------------------
#  Op library (faithful copy of the analyzer's processing operations)
# ----------------------------------------------------------------------
MORPH_OPS = {
    "Close":    cv2.MORPH_CLOSE,    "Open":     cv2.MORPH_OPEN,
    "Dilate":   cv2.MORPH_DILATE,   "Erode":    cv2.MORPH_ERODE,
    "Gradient": cv2.MORPH_GRADIENT, "TopHat":   cv2.MORPH_TOPHAT,
    "BlackHat": cv2.MORPH_BLACKHAT,
}
KERNEL_SHAPES = {
    "Rect":    cv2.MORPH_RECT,
    "Ellipse": cv2.MORPH_ELLIPSE,
    "Cross":   cv2.MORPH_CROSS,
}
RGB_DETECT_MODES = {'Color (HSV hue)': 'hue', 'Achromatic (white/gray)': 'achroma', 'Brightness (V only)': 'value', 'LAB L/a*/b* range': 'lab', 'HSV hue + LAB (red)': 'hsv_lab'}


def _odd(v):
    v = int(v)
    return v if v % 2 == 1 else v + 1


def _fill_holes(m):
    flood  = m.copy()
    h, w   = m.shape[:2]
    ffmask = np.zeros((h + 2, w + 2), np.uint8)
    cv2.floodFill(flood, ffmask, (0, 0), 255)
    return cv2.bitwise_or(m, cv2.bitwise_not(flood))


def apply_op(mask, op_name, n, kx, ky, d, thresh,
             prev=None, inp=None, kshape=cv2.MORPH_RECT):
    """Apply one morphology / extra op to a (mask or image) array."""
    n  = max(1, int(n)); kx = max(1, int(kx)); ky = max(1, int(ky))
    if op_name in MORPH_OPS:
        if d == "X":   sk = cv2.getStructuringElement(cv2.MORPH_RECT, (kx, 1))
        elif d == "Y": sk = cv2.getStructuringElement(cv2.MORPH_RECT, (1, ky))
        else:          sk = cv2.getStructuringElement(kshape,         (kx, ky))
        return cv2.morphologyEx(mask, MORPH_OPS[op_name], sk, iterations=n)
    elif op_name == "GaussBlur":
        return cv2.GaussianBlur(mask, (_odd(max(1, kx)),) * 2, 0)
    elif op_name == "MedianBlur":
        return cv2.medianBlur(mask, _odd(max(1, kx)))
    elif op_name == "BilateralBlur":
        return cv2.bilateralFilter(mask, kx, float(ky), float(ky))
    elif op_name == "Thresh_Binary":
        _, m = cv2.threshold(mask, max(0, min(255, int(thresh))),
                             255, cv2.THRESH_BINARY)
        return m
    elif op_name == "Thresh_Otsu":
        _, m = cv2.threshold(mask, 0, 255,
                             cv2.THRESH_BINARY | cv2.THRESH_OTSU)
        return m
    elif op_name == "Thresh_Adaptive":
        return cv2.adaptiveThreshold(mask, 255,
                   cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                   cv2.THRESH_BINARY, _odd(max(3, kx)), ky)
    elif op_name == "HistEq":
        return cv2.equalizeHist(mask)
    elif op_name == "CLAHE":
        cl = cv2.createCLAHE(clipLimit=float(max(1, kx)),
                             tileGridSize=(max(1, ky),) * 2)
        return cl.apply(mask)
    elif op_name == "Gamma":
        gamma = max(0.1, kx / 10.0)
        lut = np.array([min(255, int((i / 255.0) ** (1.0 / gamma) * 255))
                        for i in range(256)], dtype=np.uint8)
        return lut[mask]
    elif op_name == "Normalize":
        lo, hi = int(mask.min()), int(mask.max())
        if hi > lo:
            return cv2.normalize(mask, None, 0, 255, cv2.NORM_MINMAX)
        return mask
    elif op_name == "Retinex":
        sigma = float(max(1, kx))
        blur  = cv2.GaussianBlur(mask.astype(np.float32) + 1,
                                 (_odd(int(sigma) * 3 | 1),) * 2, sigma)
        r     = np.log1p(mask.astype(np.float32)) - np.log(blur)
        return cv2.normalize(r, None, 0, 255, cv2.NORM_MINMAX,
                             dtype=cv2.CV_8U)
    elif op_name == "Sharpen":
        k   = _odd(max(1, kx))
        blr = cv2.GaussianBlur(mask, (k, k), 0)
        return cv2.addWeighted(mask, 2.0, blr, -1.0, 0)
    elif op_name == "Laplacian":
        ksize = kx if kx in (1, 3, 5) else 3
        lap = cv2.Laplacian(mask, cv2.CV_16S, ksize=ksize)
        return cv2.convertScaleAbs(lap)
    elif op_name == "Sobel":
        ksize = kx if kx in (1, 3, 5, 7) else 3
        sx  = cv2.Sobel(mask, cv2.CV_16S, 1, 0, ksize=ksize)
        sy  = cv2.Sobel(mask, cv2.CV_16S, 0, 1, ksize=ksize)
        mag = cv2.magnitude(sx.astype(np.float32), sy.astype(np.float32))
        return cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX,
                             dtype=cv2.CV_8U)
    elif op_name == "Canny":
        return cv2.Canny(mask, max(1, kx), max(1, ky))
    elif op_name in ("AND_prev", "OR_prev", "XOR_prev"):
        ref = prev if prev is not None else mask
        if op_name == "AND_prev": return cv2.bitwise_and(mask, ref)
        if op_name == "OR_prev":  return cv2.bitwise_or(mask, ref)
        return cv2.bitwise_xor(mask, ref)
    elif op_name in ("AND_input", "OR_input", "XOR_input"):
        ref = inp if inp is not None else mask
        if op_name == "AND_input": return cv2.bitwise_and(mask, ref)
        if op_name == "OR_input":  return cv2.bitwise_or(mask, ref)
        return cv2.bitwise_xor(mask, ref)
    elif op_name == "Invert":
        return cv2.bitwise_not(mask)
    elif op_name == "FillHoles":
        return _fill_holes(mask)
    return mask


def apply_op_image(img, op_name, n, kx, ky, d, thresh,
                   kshape=cv2.MORPH_RECT):
    """Apply a PRE-MORPH op to a BGR / grayscale IMAGE (keeps colour)."""
    is_bgr = (img.ndim == 3 and img.shape[2] == 3)
    if op_name in ("GaussBlur", "MedianBlur", "BilateralBlur"):
        return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
    if op_name in ("HistEq", "CLAHE", "Gamma", "Normalize", "Retinex"):
        if not is_bgr:
            return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
        lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
        lab[:, :, 0] = apply_op(lab[:, :, 0], op_name, n, kx, ky, d,
                                thresh, kshape=kshape)
        return cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)
    if op_name == "Sharpen":
        if not is_bgr:
            return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
        return cv2.merge([apply_op(img[:, :, i], op_name, n, kx, ky, d,
                                   thresh, kshape=kshape) for i in range(3)])
    if op_name in ("Laplacian", "Sobel", "Canny"):
        if not is_bgr:
            return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        out  = apply_op(gray, op_name, n, kx, ky, d, thresh, kshape=kshape)
        return cv2.cvtColor(out, cv2.COLOR_GRAY2BGR)
    if op_name in MORPH_OPS:
        return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
    return img


def apply_pm_targeted(img, target, op_name, n, kx, ky, d, thresh,
                      kshape=cv2.MORPH_RECT):
    """Apply a PM op to the whole image OR a single HSV channel."""
    if target in ("H", "S", "V") and img.ndim == 3 and img.shape[2] == 3:
        ci   = {"H": 0, "S": 1, "V": 2}[target]
        hsv  = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        ch2  = apply_op_image(hsv[:, :, ci], op_name, n, kx, ky, d,
                              thresh, kshape=kshape)
        if ch2.ndim == 3:
            ch2 = cv2.cvtColor(ch2, cv2.COLOR_BGR2GRAY)
        if ch2.shape != hsv[:, :, ci].shape:
            ch2 = cv2.resize(ch2, (hsv.shape[1], hsv.shape[0]))
        hsv[:, :, ci] = ch2
        return cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
    return apply_op_image(img, op_name, n, kx, ky, d, thresh, kshape=kshape)


def _kshape_of(step, default_shape):
    return KERNEL_SHAPES.get(step.get("kshape", ""), default_shape)


# ----------------------------------------------------------------------
#  Pre-morph + step pipeline runners
# ----------------------------------------------------------------------
def run_pre_morph(image, pre_steps, default_shape):
    """Apply the pre-morph (image-conditioning) steps in order."""
    running = image
    for st in pre_steps:
        if not st.get("en"):
            continue
        running = apply_pm_targeted(
            running, st.get("pm_target", "BGR"), st.get("op", "GaussBlur"),
            max(1, st.get("n", 1)), max(1, st.get("kx", 3)),
            max(1, st.get("ky", 3)), st.get("dir", "XY"),
            st.get("t", 0), kshape=_kshape_of(st, default_shape))
    return running


def _coerce_mask(img, like):
    if img is None:
        return like
    m = img
    if m.ndim == 3:
        m = cv2.cvtColor(m, cv2.COLOR_BGR2GRAY)
    if m.shape != like.shape:
        m = cv2.resize(m, (like.shape[1], like.shape[0]))
    if m.dtype != like.dtype:
        m = m.astype(like.dtype)
    return m


def _resolve_src(snaps, src, mask_pre, views):
    """Resolve a combine-source name to an array."""
    if src == "mask_pre":
        return mask_pre
    if src == "prev":
        return snaps[-1] if snaps else mask_pre
    if src.startswith("step_"):
        try:
            i = int(src.split("_")[1]) - 1
            return snaps[i] if 0 <= i < len(snaps) else mask_pre
        except (ValueError, IndexError):
            return mask_pre
    if src in views:
        return views[src]
    return mask_pre   # cross-pipeline ref not available -> input mask


def run_steps(mask_pre, steps, default_shape, views, view_prefix=None):
    """Run a morph / extra-op step pipeline. Returns (final, snaps).

    `snaps` stores REFERENCES (no per-step .copy()): every op returns a
    fresh array and nothing is mutated in place, so copying each step
    just to keep a snapshot only wasted time on long pipelines.
    """
    running = mask_pre
    snaps   = []
    for idx, st in enumerate(steps):
        if not st.get("en"):
            snaps.append(running)
            if view_prefix is not None:
                views["%s_step%d" % (view_prefix, idx + 1)] = running
            continue
        if st.get("comb_en"):
            ref = _coerce_mask(
                _resolve_src(snaps, st.get("comb_src", "mask_pre"),
                             mask_pre, views), running)
            cop = st.get("comb_op", "AND")
            if cop == "AND":
                running = cv2.bitwise_and(running, ref)
            elif cop == "OR":
                running = cv2.bitwise_or(running, ref)
            elif cop == "XOR":
                running = cv2.bitwise_xor(running, ref)
            # cop == "OVERLAY": visualisation only -> mask unchanged.
        else:
            prev = snaps[-1] if snaps else None
            running = apply_op(
                running, st.get("op", "Dilate"),
                max(1, st.get("n", 1)), max(1, st.get("kx", 3)),
                max(1, st.get("ky", 3)), st.get("dir", "Both"),
                st.get("t", 0), prev=prev, inp=mask_pre,
                kshape=_kshape_of(st, default_shape))
        snaps.append(running)
        if view_prefix is not None:
            views["%s_step%d" % (view_prefix, idx + 1)] = running
    return running, snaps


# ----------------------------------------------------------------------
#  Detection
# ----------------------------------------------------------------------
def rgb_detect(bgr, P, mode_key):
    """RGB binary detection in the selected mode."""
    hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
    lab = cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB)
    smin, smax = P["S_min"], P["S_max"]
    vmin, vmax = P["V_min"], P["V_max"]
    h1l, h1h   = P["H1_low"], P["H1_high"]
    h2l, h2h   = P["H2_low"], P["H2_high"]

    def labm():
        return cv2.inRange(lab,
                           (P.get("L_min", 0), P["A_min"], P["B_min"]),
                           (P.get("L_max", 255), P["A_max"], P["B_max"]))
    if mode_key == "achroma":
        return cv2.inRange(hsv, (0, smin, vmin), (180, smax, vmax))
    if mode_key == "value":
        return cv2.inRange(hsv, (0, 0, vmin), (180, 255, vmax))
    if mode_key == "lab":
        return labm()
    if mode_key == "hsv_lab":
        a = cv2.inRange(hsv, (h1l, smin, vmin), (h1h, smax, vmax))
        b = cv2.inRange(hsv, (h2l, smin, vmin), (h2h, smax, vmax))
        return cv2.bitwise_and(cv2.bitwise_or(a, b), labm())
    # default: hue
    a = cv2.inRange(hsv, (h1l, smin, vmin), (h1h, smax, vmax))
    b = cv2.inRange(hsv, (h2l, smin, vmin), (h2h, smax, vmax))
    return cv2.bitwise_or(a, b)


def branch_rgb_detect(bgr, bd):
    """Branch RGB detection: AND of the channels named by 'channels'."""
    hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
    lab = cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB)
    h1 = cv2.inRange(hsv[:, :, 0], bd.get("h1_lo", 0),   bd.get("h1_hi", 10))
    h2 = cv2.inRange(hsv[:, :, 0], bd.get("h2_lo", 170), bd.get("h2_hi", 180))
    s  = cv2.inRange(hsv[:, :, 1], bd.get("s_lo", 0),    bd.get("s_hi", 255))
    v  = cv2.inRange(hsv[:, :, 2], bd.get("v_lo", 0),    bd.get("v_hi", 255))
    a  = cv2.inRange(lab[:, :, 1], bd.get("a_lo", 150),  bd.get("a_hi", 255))
    b  = cv2.inRange(lab[:, :, 2], bd.get("b_lo", 0),    bd.get("b_hi", 255))
    ch = bd.get("channels", "HSV")
    to_and = []
    if "H" in ch or ch == "full":
        to_and.append(cv2.bitwise_or(h1, h2))
    if "S" in ch or ch == "full":
        to_and.append(s)
    if "V" in ch or ch == "full":
        to_and.append(v)
    if "a" in ch:
        to_and.append(a)
    if "b" in ch:
        to_and.append(b)
    if not to_and:
        return np.zeros(bgr.shape[:2], np.uint8)
    det = to_and[0]
    for m in to_and[1:]:
        det = cv2.bitwise_and(det, m)
    return det


def find_objects(mask, min_area):
    """Return [(x, y, w, h), ...] for blobs at least `min_area` px."""
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL,
                               cv2.CHAIN_APPROX_SIMPLE)
    boxes = []
    for c in cnts:
        if cv2.contourArea(c) >= min_area:
            boxes.append(cv2.boundingRect(c))
    return boxes


def adjust_box(x1, y1, x2, y2, w, h, scale=1.0, pad=0):
    """Grow / shrink a YOLO box: scale (%) around its centre, then add
    `pad` pixels on every side (negative trims). Clamped to w x h.
    Lets the exported pipeline make YOLO boxes bigger (margin to
    subtract) or smaller (focus tightly inside the box)."""
    if scale != 1.0 or pad:
        cx, cy = (x1 + x2) / 2.0, (y1 + y2) / 2.0
        bw = (x2 - x1) * scale + 2 * pad
        bh = (y2 - y1) * scale + 2 * pad
        x1, x2 = cx - bw / 2.0, cx + bw / 2.0
        y1, y2 = cy - bh / 2.0, cy + bh / 2.0
    x1 = max(0, min(int(round(x1)), w - 1))
    y1 = max(0, min(int(round(y1)), h - 1))
    x2 = max(0, min(int(round(x2)), w))
    y2 = max(0, min(int(round(y2)), h))
    if x2 <= x1:
        x2 = min(w, x1 + 1)
    if y2 <= y1:
        y2 = min(h, y1 + 1)
    return x1, y1, x2, y2


# ----------------------------------------------------------------------
#  YOLO object detection (optional add-on stage). 'ultralytics' is
#  imported lazily, so a YOLO-off config never needs it installed.
# ----------------------------------------------------------------------
_YOLO_MODELS = {}


def _get_yolo_model(model_path):
    """Lazy-load (and cache) a YOLO model by weights path."""
    if model_path not in _YOLO_MODELS:
        from ultralytics import YOLO
        _YOLO_MODELS[model_path] = YOLO(model_path)
    return _YOLO_MODELS[model_path]


def run_yolo(bgr, model_path="yolo.pt", conf=0.5,
             box_scale=1.0, box_pad=0):
    """Run YOLO on a BGR image.

    Returns (boxes, mask):
      boxes - list of dicts {x, y, w, h, cls, name, conf}
      mask  - uint8 image, white inside every detected box
    `box_scale` (%/100) and `box_pad` (px) grow / shrink each box.
    """
    model = _get_yolo_model(model_path)
    boxes = []
    mask  = np.zeros(bgr.shape[:2], np.uint8)
    h, w  = bgr.shape[:2]
    for r in model(bgr, conf=conf, verbose=False):
        names = getattr(r, "names", {}) or {}
        for b in getattr(r, "boxes", []):
            x1, y1, x2, y2 = [int(v) for v in b.xyxy[0]]
            x1, y1, x2, y2 = adjust_box(x1, y1, x2, y2, w, h,
                                        box_scale, box_pad)
            cid = int(b.cls[0])
            boxes.append({"x": x1, "y": y1, "w": x2 - x1, "h": y2 - y1,
                          "cls": cid, "name": names.get(cid, str(cid)),
                          "conf": float(b.conf[0])})
            cv2.rectangle(mask, (x1, y1), (x2, y2), 255, -1)
    return boxes, mask


# ----------------------------------------------------------------------
#  Core pipeline — runs the whole config and returns every named mask.
# ----------------------------------------------------------------------
def _run_pipeline(bgr_image, ir_image, CONFIG, with_yolo):
    """Run the JSON-config pipeline. Returns (out, views).

    `out`   - dict of result masks: rgb_mask / ir_mask / combined and
              up_<branch> for each user branch (+ yolo_* when YOLO runs).
    `views` - every intermediate array, keyed by name.
    """
    P     = CONFIG.get("params", {})
    S     = CONFIG.get("strings", {})
    F     = CONFIG.get("flags", {})
    I     = CONFIG.get("ints", {})
    shape = KERNEL_SHAPES.get(S.get("kernel_shape", "Rect"), cv2.MORPH_RECT)
    mode  = RGB_DETECT_MODES.get(S.get("rgb_detect_mode", ""), "hue")

    views = {}

    # -- RGB pipeline --------------------------------------------------
    rgb_src = run_pre_morph(bgr_image, CONFIG.get("rgb_pre_pipeline", []),
                            shape)
    rgb_pre = rgb_detect(rgb_src, P, mode)
    views["rgb_mask_pre"] = rgb_pre
    rgb_mask, _ = run_steps(rgb_pre, CONFIG.get("rgb_pipeline", []),
                            shape, views, view_prefix="rgb")
    views["rgb_mask"] = rgb_mask
    views["rgb_det"]  = rgb_mask

    # -- IR pipeline ---------------------------------------------------
    if ir_image is None:
        ir_gray = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2GRAY)
    elif ir_image.ndim == 3:
        ir_gray = cv2.cvtColor(ir_image, cv2.COLOR_BGR2GRAY)
    else:
        ir_gray = ir_image
    if F.get("use_clahe_ir"):
        cl = cv2.createCLAHE(
            clipLimit=float(max(1, I.get("clahe_ir_clip", 2))),
            tileGridSize=(max(1, I.get("clahe_ir_tile", 8)),) * 2)
        ir_gray = cl.apply(ir_gray)
    ir_src    = run_pre_morph(ir_gray, CONFIG.get("ir_pre_pipeline", []),
                              shape)
    _, ir_pre = cv2.threshold(ir_src, int(P.get("IR_thresh", 128)), 255,
                              cv2.THRESH_BINARY)
    views["ir_mask_pre"] = ir_pre
    ir_mask, _ = run_steps(ir_pre, CONFIG.get("ir_pipeline", []),
                           shape, views, view_prefix="ir")
    views["ir_mask"] = ir_mask
    views["ir_det"]  = ir_mask

    combined = cv2.bitwise_or(rgb_mask, _coerce_mask(ir_mask, rgb_mask))
    views["combined"] = combined

    out = {"rgb_mask": rgb_mask, "ir_mask": ir_mask, "combined": combined}

    # -- User branches -------------------------------------------------
    for bd in CONFIG.get("user_pipelines", []):
        nm = (bd.get("name") or "branch").strip()
        bt = bd.get("type", "rgb")
        if bt == "ir":
            src = run_pre_morph(ir_gray, bd.get("pre_steps", []), shape)
            det = cv2.inRange(src, bd.get("ir_lo", 80), bd.get("ir_hi", 255))
        elif bt == "custom":
            ref = views.get(bd.get("source", ""))
            det = (_coerce_mask(ref, rgb_mask) if ref is not None
                   else np.zeros(rgb_mask.shape[:2], np.uint8))
        else:  # rgb
            src = run_pre_morph(bgr_image, bd.get("pre_steps", []), shape)
            det = branch_rgb_detect(src, bd)
        views["up_%s_det" % nm] = det
        fin, _ = run_steps(det, bd.get("steps", []), shape, views,
                           view_prefix="up_%s" % nm)
        views["up_%s" % nm]      = fin
        views["up_%s_mask" % nm] = fin
        out["up_%s" % nm]        = fin

    # -- optional YOLO stage ------------------------------------------
    if with_yolo is None:
        with_yolo = CONFIG.get("export_yolo", {}).get("enabled", False)
    if with_yolo:
        try:
            yb = CONFIG.get("export_yolo", {})
            boxes, ymask = run_yolo(bgr_image,
                                    yb.get("model_path", "yolo.pt"),
                                    yb.get("conf", 0.5),
                                    P.get("YOLO_Box_Scale", 100) / 100.0,
                                    int(P.get("YOLO_Box_Pad", 0)))
            out["yolo_boxes"] = boxes
            out["yolo_mask"]  = ymask
            views["yolo_mask"] = ymask
        except Exception as e:
            print("YOLO stage skipped (%s)" % e)

    return out, views


# ----------------------------------------------------------------------
#  Pipeline — the easy-to-use object. Build it from a JSON config, then
#  ask it for exactly the output your program wants.
# ----------------------------------------------------------------------
class Pipeline:
    """Reusable detector built from an analyzer JSON config.

    Output helpers (pick whichever your program needs):
      detect()       - dict of EVERY mask, exactly like the analyzer
      final_mask()   - ONLY the final combined binary mask  (uint8)
      mask_overlay() - the final mask painted over the image background
      mask_points()  - centre (x, y) point of every detected blob
      yolo_points()  - YOLO detections as centre points + names
    """

    def __init__(self, config):
        # `config` may be a path to a .json file or an already-loaded dict.
        if isinstance(config, str):
            with open(config, "r") as f:
                config = json.load(f)
        self.config = config or {}

    @classmethod
    def from_json(cls, path):
        """Load a Pipeline from a JSON config file path."""
        return cls(path)

    # -- full output -------------------------------------------------
    def detect(self, bgr_image, ir_image=None, with_yolo=None):
        """Run the pipeline. Returns a dict of binary masks:
        rgb_mask / ir_mask / combined, plus up_<branch> for each branch
        (and yolo_mask + yolo_boxes when YOLO is on)."""
        out, _ = _run_pipeline(bgr_image, ir_image, self.config, with_yolo)
        return out

    def views(self, bgr_image, ir_image=None, with_yolo=None):
        """Like detect() but returns EVERY intermediate array too."""
        _, views = _run_pipeline(bgr_image, ir_image, self.config,
                                 with_yolo)
        return views

    # -- only the mask -----------------------------------------------
    def final_mask(self, bgr_image, ir_image=None, key="combined"):
        """ONLY the final mask (uint8, white = detected). `key` picks
        which one: 'combined' (default), 'rgb_mask', 'ir_mask' or
        'up_<branch>'."""
        return self.detect(bgr_image, ir_image).get(key)

    # -- mask + image background -------------------------------------
    def mask_overlay(self, bgr_image, ir_image=None, key="combined",
                     color=(0, 0, 255), alpha=0.5):
        """The final mask painted (semi-transparent) over the original
        image — handy to SEE what was detected. BGR colour, default red."""
        m = self.final_mask(bgr_image, ir_image, key)
        if m is None:
            return bgr_image.copy()
        if m.ndim == 3:
            m = cv2.cvtColor(m, cv2.COLOR_BGR2GRAY)
        paint = np.zeros_like(bgr_image)
        paint[m > 0] = color
        return cv2.addWeighted(bgr_image, 1.0, paint, float(alpha), 0)

    # -- mask points -------------------------------------------------
    def mask_points(self, bgr_image, ir_image=None, key="combined",
                    min_area=None):
        """Centre point of every detected blob in the final mask.
        Returns [{x, y, w, h, area}, ...] — `x, y` is the blob centre."""
        m = self.final_mask(bgr_image, ir_image, key)
        if m is None:
            return []
        if m.ndim == 3:
            m = cv2.cvtColor(m, cv2.COLOR_BGR2GRAY)
        if min_area is None:
            min_area = self.config.get("params", {}).get("Min_area", 100)
        pts = []
        cnts, _ = cv2.findContours(m, cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_SIMPLE)
        for c in cnts:
            area = cv2.contourArea(c)
            if area < min_area:
                continue
            x, y, w, h = cv2.boundingRect(c)
            pts.append({"x": x + w // 2, "y": y + h // 2,
                        "w": w, "h": h, "area": int(area)})
        return pts

    # -- YOLO points -------------------------------------------------
    def yolo_points(self, bgr_image, conf=None):
        """YOLO detections as centre points:
        [{x, y, name, conf, w, h}, ...].  Needs `pip install ultralytics`
        and the weights file named in the config."""
        yb = self.config.get("export_yolo", {})
        _P = self.config.get("params", {})
        boxes, _ = run_yolo(bgr_image, yb.get("model_path", "yolo.pt"),
                            yb.get("conf", 0.5) if conf is None else conf,
                            _P.get("YOLO_Box_Scale", 100) / 100.0,
                            int(_P.get("YOLO_Box_Pad", 0)))
        return [{"x": b["x"] + b["w"] // 2, "y": b["y"] + b["h"] // 2,
                 "w": b["w"], "h": b["h"],
                 "name": b["name"], "conf": b["conf"]} for b in boxes]


def load_pipeline(config="config.json"):
    """Load a ready-to-use Pipeline from a JSON config file (or dict).

        pipe = load_pipeline("my_config.json")
        mask = pipe.final_mask(cv2.imread("photo.jpg"))
    """
    return Pipeline(config)


if __name__ == "__main__":
    import sys
    cfg_path = sys.argv[1] if len(sys.argv) > 1 else "config.json"
    img_path = sys.argv[2] if len(sys.argv) > 2 else None
    if not os.path.exists(cfg_path):
        print("config not found:", cfg_path)
        print("usage: python exported_pipeline_lib.py config.json [photo.jpg]")
        sys.exit(1)
    pipe = load_pipeline(cfg_path)
    if img_path and os.path.exists(img_path):
        img  = cv2.imread(img_path)
        mask = pipe.final_mask(img)
        cv2.imwrite("lib_final_mask.png", mask)
        cv2.imwrite("lib_overlay.png", pipe.mask_overlay(img))
        pts = pipe.mask_points(img)
        print("final mask  -> lib_final_mask.png")
        print("overlay     -> lib_overlay.png")
        print("mask points -> %d blob(s):" % len(pts))
        for p in pts:
            print("   x=%d y=%d area=%d" % (p["x"], p["y"], p["area"]))
    else:
        print("Pipeline loaded OK from", cfg_path)
        print("pass an image to test:  python exported_pipeline_lib.py %s photo.jpg"
              % cfg_path)
