"""Exported RealSense Cable detection pipeline.

Auto-generated by the RealSense Cable Video Analyzer.
Self-contained: needs only opencv-python + numpy.

Usage as a library:
    from exported_pipeline import detect
    import cv2
    masks = detect(cv2.imread('photo.jpg'))
    cv2.imwrite('mask.png', masks['combined'])

Usage from the command line:
    python exported_pipeline.py photo.jpg [ir.png]

See the exported_pipeline_examples/ folder for 7 worked examples.

YOLO: when the analyzer had 'Use YOLO' ticked, detect()
runs YOLO too (adds 'yolo_mask' + 'yolo_boxes'). It needs
`pip install ultralytics` and the weights file; ultralytics
is imported lazily so a YOLO-off config never needs it.

NOT reproduced: MOG2 background subtraction (needs video
history) and the OVERLAY combine (visualisation-only).
"""
import os
import json
import cv2
import numpy as np

# ---- Tuned configuration (snapshot of the GUI) ----
CONFIG = json.loads(r'''
{
 "version": 1,
 "params": {
  "H1_low": 0,
  "H1_high": 10,
  "H2_low": 160,
  "H2_high": 180,
  "S_min": 80,
  "S_max": 255,
  "V_min": 40,
  "V_max": 255,
  "A_min": 150,
  "A_max": 255,
  "B_min": 0,
  "B_max": 255,
  "BG_hist_rgb": 500,
  "BG_var_rgb": 50,
  "IR_thresh": 100,
  "BG_hist_ir": 500,
  "BG_var_ir": 50,
  "YOLO_Conf": 50,
  "Min_area": 20
 },
 "flags": {
  "use_bgsub_rgb": true,
  "use_bgsub_ir": true,
  "show_boxes": true,
  "show_overlay": true,
  "use_yolo": true,
  "loop_var": false,
  "use_clahe_ir": false
 },
 "ints": {
  "clahe_ir_clip": 2,
  "clahe_ir_tile": 8
 },
 "strings": {
  "rgb_detect_mode": "Color (HSV hue)",
  "ir_cmap": "Gray",
  "kernel_shape": "Rect",
  "rgb_mask_color": "#ff0000",
  "ir_mask_color": "#ffff00",
  "yolo_mask_color": "#ff00ff",
  "bgsub_rgb_src": "auto",
  "bgsub_ir_src": "auto"
 },
 "rgb_pipeline": [
  {
   "en": true,
   "op": "Close",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Open",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Erode",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 0,
   "comb_en": true,
   "comb_op": "OR",
   "comb_src": "mask_pre"
  },
  {
   "en": true,
   "op": "TopHat",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "BlackHat",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "GaussBlur",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "MedianBlur",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 0,
   "comb_en": true,
   "comb_op": "OR",
   "comb_src": "mask_pre"
  },
  {
   "en": true,
   "op": "Invert",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "FillHoles",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Thresh_Otsu",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Close",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 0,
   "comb_en": true,
   "comb_op": "OR",
   "comb_src": "mask_pre"
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Erode",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Gradient",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "TopHat",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 0,
   "comb_en": true,
   "comb_op": "OR",
   "comb_src": "mask_pre"
  }
 ],
 "ir_pipeline": [
  {
   "en": true,
   "op": "Close",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Open",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Erode",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 0,
   "comb_en": true,
   "comb_op": "OR",
   "comb_src": "mask_pre"
  },
  {
   "en": true,
   "op": "TopHat",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "BlackHat",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "GaussBlur",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "MedianBlur",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 0,
   "comb_en": true,
   "comb_op": "OR",
   "comb_src": "mask_pre"
  },
  {
   "en": true,
   "op": "Invert",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "FillHoles",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Thresh_Otsu",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Close",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 0,
   "comb_en": true,
   "comb_op": "OR",
   "comb_src": "mask_pre"
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Erode",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Gradient",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "TopHat",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 120
  },
  {
   "en": true,
   "op": "Dilate",
   "n": 1,
   "dir": "Both",
   "kx": 3,
   "ky": 3,
   "t": 0,
   "comb_en": true,
   "comb_op": "OR",
   "comb_src": "mask_pre"
  }
 ],
 "rgb_pre_pipeline": [
  {
   "en": true,
   "op": "GaussBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "MedianBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "BilateralBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "CLAHE",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Gamma",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Sharpen",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Normalize",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "HistEq",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "GaussBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "MedianBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "BilateralBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "CLAHE",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Gamma",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Sharpen",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Normalize",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "HistEq",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "GaussBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "MedianBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "BilateralBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "CLAHE",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  }
 ],
 "ir_pre_pipeline": [
  {
   "en": true,
   "op": "GaussBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "MedianBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "BilateralBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "CLAHE",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Gamma",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Sharpen",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Normalize",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "HistEq",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "GaussBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "MedianBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "BilateralBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "CLAHE",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Gamma",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Sharpen",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "Normalize",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "HistEq",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "GaussBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "MedianBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "BilateralBlur",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  },
  {
   "en": true,
   "op": "CLAHE",
   "n": 1,
   "dir": "XY",
   "kx": 5,
   "ky": 5,
   "t": 0
  }
 ],
 "user_pipelines": [
  {
   "name": "maxrgb",
   "type": "rgb",
   "steps": [
    {
     "en": true,
     "op": "Close",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Open",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Erode",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "TopHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "BlackHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "Invert",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "FillHoles",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Thresh_Otsu",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Close",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Erode",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Gradient",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "TopHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    }
   ],
   "pre_steps": [
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Gamma",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Sharpen",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Normalize",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "HistEq",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Gamma",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Sharpen",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Normalize",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "HistEq",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    }
   ],
   "channels": "HSVab"
  },
  {
   "name": "maxir",
   "type": "ir",
   "steps": [
    {
     "en": true,
     "op": "Close",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Open",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Erode",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "TopHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "BlackHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "Invert",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "FillHoles",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Thresh_Otsu",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Close",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Erode",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Gradient",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "TopHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    }
   ],
   "pre_steps": [
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Gamma",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Sharpen",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Normalize",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "HistEq",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Gamma",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Sharpen",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Normalize",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "HistEq",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    }
   ]
  },
  {
   "name": "maxcustom",
   "type": "custom",
   "steps": [
    {
     "en": true,
     "op": "Close",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Open",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Erode",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "TopHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "BlackHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "Invert",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "FillHoles",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Thresh_Otsu",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Close",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Erode",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Gradient",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "TopHat",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 120
    },
    {
     "en": true,
     "op": "Dilate",
     "n": 1,
     "dir": "Both",
     "kx": 3,
     "ky": 3,
     "t": 0,
     "comb_en": true,
     "comb_op": "OR",
     "comb_src": "mask_pre"
    }
   ],
   "pre_steps": [
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Gamma",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Sharpen",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Normalize",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "HistEq",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Gamma",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Sharpen",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "Normalize",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "HistEq",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "GaussBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "MedianBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "BilateralBlur",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    },
    {
     "en": true,
     "op": "CLAHE",
     "n": 1,
     "dir": "XY",
     "kx": 5,
     "ky": 5,
     "t": 0
    }
   ],
   "source": "rgb_mask"
  }
 ],
 "export_yolo": {
  "enabled": true,
  "model_path": "/home/mannaja/intern_in_MuroranIT/intern_program/models/drone_t_hook.pt",
  "conf": 0.5
 }
}
''')

# ----------------------------------------------------------------------
#  Op library (faithful copy of the analyzer's processing operations)
# ----------------------------------------------------------------------
MORPH_OPS = {
    "Close":    cv2.MORPH_CLOSE,    "Open":     cv2.MORPH_OPEN,
    "Dilate":   cv2.MORPH_DILATE,   "Erode":    cv2.MORPH_ERODE,
    "Gradient": cv2.MORPH_GRADIENT, "TopHat":   cv2.MORPH_TOPHAT,
    "BlackHat": cv2.MORPH_BLACKHAT,
}
KERNEL_SHAPES = {
    "Rect":    cv2.MORPH_RECT,
    "Ellipse": cv2.MORPH_ELLIPSE,
    "Cross":   cv2.MORPH_CROSS,
}
RGB_DETECT_MODES = {'Color (HSV hue)': 'hue', 'Achromatic (white/gray)': 'achroma', 'Brightness (V only)': 'value', 'LAB a*b* range': 'lab', 'HSV hue + LAB (red)': 'hsv_lab'}


def _odd(v):
    v = int(v)
    return v if v % 2 == 1 else v + 1


def _fill_holes(m):
    flood  = m.copy()
    h, w   = m.shape[:2]
    ffmask = np.zeros((h + 2, w + 2), np.uint8)
    cv2.floodFill(flood, ffmask, (0, 0), 255)
    return cv2.bitwise_or(m, cv2.bitwise_not(flood))


def apply_op(mask, op_name, n, kx, ky, d, thresh,
             prev=None, inp=None, kshape=cv2.MORPH_RECT):
    """Apply one morphology / extra op to a (mask or image) array."""
    n  = max(1, int(n)); kx = max(1, int(kx)); ky = max(1, int(ky))
    if op_name in MORPH_OPS:
        if d == "X":   sk = cv2.getStructuringElement(cv2.MORPH_RECT, (kx, 1))
        elif d == "Y": sk = cv2.getStructuringElement(cv2.MORPH_RECT, (1, ky))
        else:          sk = cv2.getStructuringElement(kshape,         (kx, ky))
        return cv2.morphologyEx(mask, MORPH_OPS[op_name], sk, iterations=n)
    elif op_name == "GaussBlur":
        return cv2.GaussianBlur(mask, (_odd(max(1, kx)),) * 2, 0)
    elif op_name == "MedianBlur":
        return cv2.medianBlur(mask, _odd(max(1, kx)))
    elif op_name == "BilateralBlur":
        return cv2.bilateralFilter(mask, kx, float(ky), float(ky))
    elif op_name == "Thresh_Binary":
        _, m = cv2.threshold(mask, max(0, min(255, int(thresh))),
                             255, cv2.THRESH_BINARY)
        return m
    elif op_name == "Thresh_Otsu":
        _, m = cv2.threshold(mask, 0, 255,
                             cv2.THRESH_BINARY | cv2.THRESH_OTSU)
        return m
    elif op_name == "Thresh_Adaptive":
        return cv2.adaptiveThreshold(mask, 255,
                   cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                   cv2.THRESH_BINARY, _odd(max(3, kx)), ky)
    elif op_name == "HistEq":
        return cv2.equalizeHist(mask)
    elif op_name == "CLAHE":
        cl = cv2.createCLAHE(clipLimit=float(max(1, kx)),
                             tileGridSize=(max(1, ky),) * 2)
        return cl.apply(mask)
    elif op_name == "Gamma":
        gamma = max(0.1, kx / 10.0)
        lut = np.array([min(255, int((i / 255.0) ** (1.0 / gamma) * 255))
                        for i in range(256)], dtype=np.uint8)
        return lut[mask]
    elif op_name == "Normalize":
        lo, hi = int(mask.min()), int(mask.max())
        if hi > lo:
            return cv2.normalize(mask, None, 0, 255, cv2.NORM_MINMAX)
        return mask
    elif op_name == "Retinex":
        sigma = float(max(1, kx))
        blur  = cv2.GaussianBlur(mask.astype(np.float32) + 1,
                                 (_odd(int(sigma) * 3 | 1),) * 2, sigma)
        r     = np.log1p(mask.astype(np.float32)) - np.log(blur)
        return cv2.normalize(r, None, 0, 255, cv2.NORM_MINMAX,
                             dtype=cv2.CV_8U)
    elif op_name == "Sharpen":
        k   = _odd(max(1, kx))
        blr = cv2.GaussianBlur(mask, (k, k), 0)
        return cv2.addWeighted(mask, 2.0, blr, -1.0, 0)
    elif op_name == "Laplacian":
        ksize = kx if kx in (1, 3, 5) else 3
        lap = cv2.Laplacian(mask, cv2.CV_16S, ksize=ksize)
        return cv2.convertScaleAbs(lap)
    elif op_name == "Sobel":
        ksize = kx if kx in (1, 3, 5, 7) else 3
        sx  = cv2.Sobel(mask, cv2.CV_16S, 1, 0, ksize=ksize)
        sy  = cv2.Sobel(mask, cv2.CV_16S, 0, 1, ksize=ksize)
        mag = cv2.magnitude(sx.astype(np.float32), sy.astype(np.float32))
        return cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX,
                             dtype=cv2.CV_8U)
    elif op_name == "Canny":
        return cv2.Canny(mask, max(1, kx), max(1, ky))
    elif op_name in ("AND_prev", "OR_prev", "XOR_prev"):
        ref = prev if prev is not None else mask
        if op_name == "AND_prev": return cv2.bitwise_and(mask, ref)
        if op_name == "OR_prev":  return cv2.bitwise_or(mask, ref)
        return cv2.bitwise_xor(mask, ref)
    elif op_name in ("AND_input", "OR_input", "XOR_input"):
        ref = inp if inp is not None else mask
        if op_name == "AND_input": return cv2.bitwise_and(mask, ref)
        if op_name == "OR_input":  return cv2.bitwise_or(mask, ref)
        return cv2.bitwise_xor(mask, ref)
    elif op_name == "Invert":
        return cv2.bitwise_not(mask)
    elif op_name == "FillHoles":
        return _fill_holes(mask)
    return mask


def apply_op_image(img, op_name, n, kx, ky, d, thresh,
                   kshape=cv2.MORPH_RECT):
    """Apply a PRE-MORPH op to a BGR / grayscale IMAGE (keeps colour)."""
    is_bgr = (img.ndim == 3 and img.shape[2] == 3)
    if op_name in ("GaussBlur", "MedianBlur", "BilateralBlur"):
        return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
    if op_name in ("HistEq", "CLAHE", "Gamma", "Normalize", "Retinex"):
        if not is_bgr:
            return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
        lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
        lab[:, :, 0] = apply_op(lab[:, :, 0], op_name, n, kx, ky, d,
                                thresh, kshape=kshape)
        return cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)
    if op_name == "Sharpen":
        if not is_bgr:
            return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
        return cv2.merge([apply_op(img[:, :, i], op_name, n, kx, ky, d,
                                   thresh, kshape=kshape) for i in range(3)])
    if op_name in ("Laplacian", "Sobel", "Canny"):
        if not is_bgr:
            return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        out  = apply_op(gray, op_name, n, kx, ky, d, thresh, kshape=kshape)
        return cv2.cvtColor(out, cv2.COLOR_GRAY2BGR)
    if op_name in MORPH_OPS:
        return apply_op(img, op_name, n, kx, ky, d, thresh, kshape=kshape)
    return img


def apply_pm_targeted(img, target, op_name, n, kx, ky, d, thresh,
                      kshape=cv2.MORPH_RECT):
    """Apply a PM op to the whole image OR a single HSV channel."""
    if target in ("H", "S", "V") and img.ndim == 3 and img.shape[2] == 3:
        ci   = {"H": 0, "S": 1, "V": 2}[target]
        hsv  = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        ch2  = apply_op_image(hsv[:, :, ci], op_name, n, kx, ky, d,
                              thresh, kshape=kshape)
        if ch2.ndim == 3:
            ch2 = cv2.cvtColor(ch2, cv2.COLOR_BGR2GRAY)
        if ch2.shape != hsv[:, :, ci].shape:
            ch2 = cv2.resize(ch2, (hsv.shape[1], hsv.shape[0]))
        hsv[:, :, ci] = ch2
        return cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
    return apply_op_image(img, op_name, n, kx, ky, d, thresh, kshape=kshape)


def _kshape_of(step, default_shape):
    return KERNEL_SHAPES.get(step.get("kshape", ""), default_shape)


# ----------------------------------------------------------------------
#  Pre-morph + step pipeline runners
# ----------------------------------------------------------------------
def run_pre_morph(image, pre_steps, default_shape):
    """Apply the pre-morph (image-conditioning) steps in order."""
    running = image
    for st in pre_steps:
        if not st.get("en"):
            continue
        running = apply_pm_targeted(
            running, st.get("pm_target", "BGR"), st.get("op", "GaussBlur"),
            max(1, st.get("n", 1)), max(1, st.get("kx", 3)),
            max(1, st.get("ky", 3)), st.get("dir", "XY"),
            st.get("t", 0), kshape=_kshape_of(st, default_shape))
    return running


def _coerce_mask(img, like):
    if img is None:
        return like
    m = img
    if m.ndim == 3:
        m = cv2.cvtColor(m, cv2.COLOR_BGR2GRAY)
    if m.shape != like.shape:
        m = cv2.resize(m, (like.shape[1], like.shape[0]))
    if m.dtype != like.dtype:
        m = m.astype(like.dtype)
    return m


def _resolve_src(snaps, src, mask_pre, views):
    """Resolve a combine-source name to an array."""
    if src == "mask_pre":
        return mask_pre
    if src == "prev":
        return snaps[-1] if snaps else mask_pre
    if src.startswith("step_"):
        try:
            i = int(src.split("_")[1]) - 1
            return snaps[i] if 0 <= i < len(snaps) else mask_pre
        except (ValueError, IndexError):
            return mask_pre
    if src in views:
        return views[src]
    return mask_pre   # cross-pipeline ref not available -> input mask


def run_steps(mask_pre, steps, default_shape, views, view_prefix=None):
    """Run a morph / extra-op step pipeline. Returns (final, snaps).

    `snaps` stores REFERENCES (no per-step .copy()): every op returns a
    fresh array and nothing is mutated in place, so copying each step
    just to keep a snapshot only wasted time on long pipelines.
    """
    running = mask_pre
    snaps   = []
    for idx, st in enumerate(steps):
        if not st.get("en"):
            snaps.append(running)
            if view_prefix is not None:
                views["%s_step%d" % (view_prefix, idx + 1)] = running
            continue
        if st.get("comb_en"):
            ref = _coerce_mask(
                _resolve_src(snaps, st.get("comb_src", "mask_pre"),
                             mask_pre, views), running)
            cop = st.get("comb_op", "AND")
            if cop == "AND":
                running = cv2.bitwise_and(running, ref)
            elif cop == "OR":
                running = cv2.bitwise_or(running, ref)
            elif cop == "XOR":
                running = cv2.bitwise_xor(running, ref)
            # cop == "OVERLAY": visualisation only -> mask unchanged.
        else:
            prev = snaps[-1] if snaps else None
            running = apply_op(
                running, st.get("op", "Dilate"),
                max(1, st.get("n", 1)), max(1, st.get("kx", 3)),
                max(1, st.get("ky", 3)), st.get("dir", "Both"),
                st.get("t", 0), prev=prev, inp=mask_pre,
                kshape=_kshape_of(st, default_shape))
        snaps.append(running)
        if view_prefix is not None:
            views["%s_step%d" % (view_prefix, idx + 1)] = running
    return running, snaps


# ----------------------------------------------------------------------
#  Detection
# ----------------------------------------------------------------------
def rgb_detect(bgr, P, mode_key):
    """RGB binary detection in the selected mode."""
    hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
    lab = cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB)
    smin, smax = P["S_min"], P["S_max"]
    vmin, vmax = P["V_min"], P["V_max"]
    h1l, h1h   = P["H1_low"], P["H1_high"]
    h2l, h2h   = P["H2_low"], P["H2_high"]

    def labm():
        return cv2.inRange(lab, (0, P["A_min"], P["B_min"]),
                                (255, P["A_max"], P["B_max"]))
    if mode_key == "achroma":
        return cv2.inRange(hsv, (0, smin, vmin), (180, smax, vmax))
    if mode_key == "value":
        return cv2.inRange(hsv, (0, 0, vmin), (180, 255, vmax))
    if mode_key == "lab":
        return labm()
    if mode_key == "hsv_lab":
        a = cv2.inRange(hsv, (h1l, smin, vmin), (h1h, smax, vmax))
        b = cv2.inRange(hsv, (h2l, smin, vmin), (h2h, smax, vmax))
        return cv2.bitwise_and(cv2.bitwise_or(a, b), labm())
    # default: hue
    a = cv2.inRange(hsv, (h1l, smin, vmin), (h1h, smax, vmax))
    b = cv2.inRange(hsv, (h2l, smin, vmin), (h2h, smax, vmax))
    return cv2.bitwise_or(a, b)


def branch_rgb_detect(bgr, bd):
    """Branch RGB detection: AND of the channels named by 'channels'."""
    hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
    lab = cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB)
    h1 = cv2.inRange(hsv[:, :, 0], bd.get("h1_lo", 0),   bd.get("h1_hi", 10))
    h2 = cv2.inRange(hsv[:, :, 0], bd.get("h2_lo", 170), bd.get("h2_hi", 180))
    s  = cv2.inRange(hsv[:, :, 1], bd.get("s_lo", 0),    bd.get("s_hi", 255))
    v  = cv2.inRange(hsv[:, :, 2], bd.get("v_lo", 0),    bd.get("v_hi", 255))
    a  = cv2.inRange(lab[:, :, 1], bd.get("a_lo", 150),  bd.get("a_hi", 255))
    b  = cv2.inRange(lab[:, :, 2], bd.get("b_lo", 0),    bd.get("b_hi", 255))
    ch = bd.get("channels", "HSV")
    to_and = []
    if "H" in ch or ch == "full":
        to_and.append(cv2.bitwise_or(h1, h2))
    if "S" in ch or ch == "full":
        to_and.append(s)
    if "V" in ch or ch == "full":
        to_and.append(v)
    if "a" in ch:
        to_and.append(a)
    if "b" in ch:
        to_and.append(b)
    if not to_and:
        return np.zeros(bgr.shape[:2], np.uint8)
    det = to_and[0]
    for m in to_and[1:]:
        det = cv2.bitwise_and(det, m)
    return det


def find_objects(mask, min_area):
    """Return [(x, y, w, h), ...] for blobs at least `min_area` px."""
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL,
                               cv2.CHAIN_APPROX_SIMPLE)
    boxes = []
    for c in cnts:
        if cv2.contourArea(c) >= min_area:
            boxes.append(cv2.boundingRect(c))
    return boxes


# ----------------------------------------------------------------------
#  YOLO object detection (optional add-on stage)
#
#  The 'ultralytics' package is imported LAZILY inside _get_yolo_model,
#  so a config with YOLO disabled never needs it installed. When the
#  analyzer had "Use YOLO" ticked, detect() runs this automatically.
# ----------------------------------------------------------------------
_YOLO_MODEL = None


def _get_yolo_model():
    """Lazy-load the YOLO model (imports ultralytics only when called)."""
    global _YOLO_MODEL
    if _YOLO_MODEL is None:
        from ultralytics import YOLO
        path = CONFIG.get("export_yolo", {}).get("model_path", "yolo.pt")
        _YOLO_MODEL = YOLO(path)
    return _YOLO_MODEL


def run_yolo(bgr, conf=None):
    """Run YOLO on a BGR image.

    Returns (boxes, mask):
      boxes - list of dicts {x, y, w, h, cls, name, conf}
      mask  - uint8 image, white inside every detected box
    Needs `pip install ultralytics` and the model weights file
    (path is baked into CONFIG['export_yolo']['model_path']).
    """
    if conf is None:
        conf = CONFIG.get("export_yolo", {}).get("conf", 0.5)
    model = _get_yolo_model()
    boxes = []
    mask  = np.zeros(bgr.shape[:2], np.uint8)
    for r in model(bgr, conf=conf, verbose=False):
        names = getattr(r, "names", {}) or {}
        for b in getattr(r, "boxes", []):
            x1, y1, x2, y2 = [int(v) for v in b.xyxy[0]]
            cid = int(b.cls[0])
            boxes.append({"x": x1, "y": y1, "w": x2 - x1, "h": y2 - y1,
                          "cls": cid, "name": names.get(cid, str(cid)),
                          "conf": float(b.conf[0])})
            cv2.rectangle(mask, (x1, y1), (x2, y2), 255, -1)
    return boxes, mask


# ----------------------------------------------------------------------
#  Top-level pipeline
# ----------------------------------------------------------------------
def detect(bgr_image, ir_image=None, with_yolo=None):
    """Run the exported pipeline on one BGR image.

    `ir_image` is optional — when omitted the IR pipeline runs on the
    grayscale of the RGB image (same as the analyzer's RGB-only mode).

    `with_yolo` - None = follow the exported config; True/False forces
    the YOLO stage on/off.

    Returns a dict of binary masks: 'rgb_mask', 'ir_mask', 'combined',
    plus 'up_<branch>' for every user branch. When YOLO runs it also
    adds 'yolo_mask' (uint8) and 'yolo_boxes' (list of dicts).
    """
    P     = CONFIG["params"]
    S     = CONFIG.get("strings", {})
    F     = CONFIG.get("flags", {})
    I     = CONFIG.get("ints", {})
    shape = KERNEL_SHAPES.get(S.get("kernel_shape", "Rect"), cv2.MORPH_RECT)
    mode  = RGB_DETECT_MODES.get(S.get("rgb_detect_mode", ""), "hue")

    views = {}

    # -- RGB pipeline --------------------------------------------------
    rgb_src   = run_pre_morph(bgr_image, CONFIG.get("rgb_pre_pipeline", []),
                              shape)
    rgb_pre   = rgb_detect(rgb_src, P, mode)
    views["rgb_mask_pre"] = rgb_pre
    rgb_mask, _ = run_steps(rgb_pre, CONFIG.get("rgb_pipeline", []),
                            shape, views, view_prefix="rgb")
    views["rgb_mask"] = rgb_mask
    views["rgb_det"]  = rgb_mask

    # -- IR pipeline ---------------------------------------------------
    if ir_image is None:
        ir_gray = cv2.cvtColor(bgr_image, cv2.COLOR_BGR2GRAY)
    elif ir_image.ndim == 3:
        ir_gray = cv2.cvtColor(ir_image, cv2.COLOR_BGR2GRAY)
    else:
        ir_gray = ir_image
    if F.get("use_clahe_ir"):
        cl = cv2.createCLAHE(
            clipLimit=float(max(1, I.get("clahe_ir_clip", 2))),
            tileGridSize=(max(1, I.get("clahe_ir_tile", 8)),) * 2)
        ir_gray = cl.apply(ir_gray)
    ir_src    = run_pre_morph(ir_gray, CONFIG.get("ir_pre_pipeline", []),
                              shape)
    _, ir_pre = cv2.threshold(ir_src, int(P["IR_thresh"]), 255,
                              cv2.THRESH_BINARY)
    views["ir_mask_pre"] = ir_pre
    ir_mask, _ = run_steps(ir_pre, CONFIG.get("ir_pipeline", []),
                           shape, views, view_prefix="ir")
    views["ir_mask"] = ir_mask
    views["ir_det"]  = ir_mask

    combined = cv2.bitwise_or(rgb_mask, _coerce_mask(ir_mask, rgb_mask))
    views["combined"] = combined

    out = {"rgb_mask": rgb_mask, "ir_mask": ir_mask, "combined": combined}

    # -- User branches -------------------------------------------------
    for bd in CONFIG.get("user_pipelines", []):
        nm = (bd.get("name") or "branch").strip()
        bt = bd.get("type", "rgb")
        if bt == "ir":
            src  = run_pre_morph(ir_gray, bd.get("pre_steps", []), shape)
            det  = cv2.inRange(src, bd.get("ir_lo", 80),
                                    bd.get("ir_hi", 255))
        elif bt == "custom":
            ref  = views.get(bd.get("source", ""))
            det  = (_coerce_mask(ref, rgb_mask) if ref is not None
                    else np.zeros(rgb_mask.shape[:2], np.uint8))
        else:  # rgb
            src  = run_pre_morph(bgr_image, bd.get("pre_steps", []), shape)
            det  = branch_rgb_detect(src, bd)
        views["up_%s_det" % nm] = det
        fin, _ = run_steps(det, bd.get("steps", []), shape, views,
                           view_prefix="up_%s" % nm)
        views["up_%s" % nm]      = fin
        views["up_%s_mask" % nm] = fin
        out["up_%s" % nm]        = fin

    # -- optional YOLO stage ------------------------------------------
    if with_yolo is None:
        with_yolo = CONFIG.get("export_yolo", {}).get("enabled", False)
    if with_yolo:
        try:
            boxes, ymask = run_yolo(bgr_image)
            out["yolo_boxes"] = boxes
            out["yolo_mask"]  = ymask
        except Exception as e:
            print("YOLO stage skipped (%s)" % e)

    return out


if __name__ == "__main__":
    import sys
    src = sys.argv[1] if len(sys.argv) > 1 else "test.jpg"
    img = cv2.imread(src)
    if img is None:
        print("Could not read image:", src)
        sys.exit(1)
    ir = None
    if len(sys.argv) > 2:
        ir = cv2.imread(sys.argv[2])
    result = detect(img, ir)
    base = os.path.splitext(os.path.basename(src))[0]
    for name, value in result.items():
        if isinstance(value, np.ndarray):
            out_name = "%s_%s.png" % (base, name)
            cv2.imwrite(out_name, value)
            print("wrote", out_name)
    # Bounding boxes of the combined mask (Min_area filter).
    boxes = find_objects(result["combined"],
                         CONFIG["params"].get("Min_area", 100))
    print("objects (combined, area >= Min_area):", len(boxes))
    for (x, y, w, h) in boxes:
        print("  box x=%d y=%d w=%d h=%d" % (x, y, w, h))
    # YOLO detections, when the exported config had YOLO enabled.
    if "yolo_boxes" in result:
        print("YOLO detections:", len(result["yolo_boxes"]))
        for d in result["yolo_boxes"]:
            print("  %s  conf=%.2f  x=%d y=%d w=%d h=%d"
                  % (d["name"], d["conf"], d["x"], d["y"],
                     d["w"], d["h"]))
